version: '3'

vars:
  DOCKER_IMAGE: govcraft/latin-experiment
  VERSION:
    sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the latin-experiment binary (release)
    cmds:
      - cargo build --release -p latin-experiment

  test:
    desc: Run tests
    cmds:
      - cargo nextest run -p latin-experiment

  check:
    desc: Check code compiles
    cmds:
      - cargo check -p latin-experiment

  docker:build:
    desc: Build Docker image for RunPod (tagged with version and latest)
    deps: [build]
    cmds:
      - cp target/release/latin-experiment runpod-template/
      - cp run-experiments.sh runpod-template/
      - echo "Building {{.DOCKER_IMAGE}}:{{.VERSION}} and :latest"
      - docker build --platform linux/amd64 -t {{.DOCKER_IMAGE}}:{{.VERSION}} -t {{.DOCKER_IMAGE}}:latest runpod-template/

  docker:push:
    desc: Push Docker image to Docker Hub (version and latest tags)
    cmds:
      - docker push {{.DOCKER_IMAGE}}:{{.VERSION}}
      - docker push {{.DOCKER_IMAGE}}:latest

  docker:rebuild:
    desc: Rebuild and push Docker image (full workflow)
    cmds:
      - task: docker:build
      - task: docker:push

  paper:
    desc: Compile the paper
    cmds:
      - typst compile paper/main.typ

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
      - rm -f runpod-template/latin-experiment
