version: '3'

vars:
  VERSION:
    sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the schedule-experiment binary (release)
    cmds:
      - cargo build --release -p schedule-experiment

  test:
    desc: Run tests
    cmds:
      - cargo nextest run

  check:
    desc: Check code compiles
    cmds:
      - cargo check

  paper:
    desc: Compile the paper
    cmds:
      - typst compile paper/main.typ

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
